name: ci

on:
  pull_request:
    branches:
      - dev
      - main

permissions:
  actions: read
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn Version
        run: corepack prepare yarn@4.1.0 --activate

      - run: |
          git rev-parse --verify main || git remote set-branches origin main && \
          git fetch --depth 1 origin main && git branch main origin/main

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn run build

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn run test
