name: Documentation
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docs:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn Version
        run: corepack prepare yarn@4.1.0 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build documentation
        run: yarn docs

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          clean: true
